[package]
name = "rbq"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = "51.0.0"
arrow-array = "51.0.0"
futures = "0.3.30"
parquet = "51.0.0"
tokio = { version = "1.37.0", features = ["full"] }
clap = { version= "4.5.4", features=["derive"] }

[[bin]]
name = "rbq"
path = "src/cli.rs"
